# Generated by Django 4.2.29 on 2026-03-16 21:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tagline', models.CharField(blank=True, default='О нас', max_length=100)),
                ('hero_title', models.CharField(default='Тихая красота природы', max_length=200)),
                ('hero_subtitle', wagtail.fields.RichTextField(blank=True)),
                ('story_title', models.CharField(blank=True, default='История бренда', max_length=200)),
                ('story_body', wagtail.fields.RichTextField(blank=True)),
                ('values_title', models.CharField(blank=True, default='Наши ценности', max_length=200)),
                ('value_one_title', models.CharField(blank=True, max_length=100)),
                ('value_one_body', models.TextField(blank=True)),
                ('value_two_title', models.CharField(blank=True, max_length=100)),
                ('value_two_body', models.TextField(blank=True)),
                ('value_three_title', models.CharField(blank=True, max_length=100)),
                ('value_three_body', models.TextField(blank=True)),
                ('value_four_title', models.CharField(blank=True, max_length=100)),
                ('value_four_body', models.TextField(blank=True)),
                ('closing_quote', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Страница о бренде',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CatalogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(default='Коллекция', max_length=200)),
                ('intro_body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Каталог',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro_title', models.CharField(default='Связаться с нами', max_length=200)),
                ('intro_body', wagtail.fields.RichTextField(blank=True)),
                ('thank_you_title', models.CharField(default='Спасибо', max_length=200)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Страница контактов',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('collection_name', models.CharField(blank=True, max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('fabric_info', models.TextField(blank=True, verbose_name='О ткани')),
                ('care_info', models.TextField(blank=True, verbose_name='Уход')),
                ('status', models.CharField(choices=[('available', 'В наличии'), ('coming_soon', 'Скоро'), ('sold_out', 'Нет в наличии')], default='available', max_length=20)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='website.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
