# Generated by Django 4.2.29 on 2026-03-20 14:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('headline', models.CharField(default='Доставка и возврат', max_length=200)),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Первый абзац')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Второй абзац')),
                ('bottom_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение внизу')),
            ],
            options={
                'verbose_name': 'Доставка и возврат',
            },
            bases=('wagtailcore.page',),
        ),
    ]
