# Generated by Django 4.2.29 on 2026-08-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_legalpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogpage',
            name='intro_title',
            field=models.CharField(blank=True, default='Коллекция', max_length=200),
        ),
    ]
