# Generated by Django 4.2.29 on 2026-09-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_order_payment_idempotence_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_preorder',
            field=models.BooleanField(default=False, help_text='Оформлен в режиме SALES_MODE=preorder — оплата через ЮKassa для него не запрашивалась.', verbose_name='Предзаказ'),
        ),
    ]
