# Generated by Django 4.2.29 on 2026-09-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_order_is_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='color',
            field=models.CharField(choices=[('milk', 'Молочный'), ('olive', 'Оливковый')], default='milk', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='print_type',
            field=models.CharField(choices=[('embroidery', 'Вышивка'), ('print', 'Печать')], default='print', max_length=20, verbose_name='Тип принта'),
        ),
    ]
