# Generated by Django 4.2.29 on 2026-09-19 20:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_productpage_color_productpage_print_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='closing_quote',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='story_body',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='story_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='value_four_body',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='value_four_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='value_one_body',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='value_one_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='value_three_body',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='value_three_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='value_two_body',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='value_two_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='values_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', wagtail.blocks.StructBlock([('eyebrow', wagtail.blocks.CharBlock(label='Надпись над заголовком', max_length=100, required=False)), ('headline', wagtail.blocks.CharBlock(label='Главный заголовок', max_length=200)), ('subheadline', wagtail.blocks.CharBlock(label='Подзаголовок', max_length=300, required=False)), ('cta_text', wagtail.blocks.CharBlock(default='Смотреть каталог', label='Текст кнопки', max_length=100)), ('cta_url', wagtail.blocks.CharBlock(help_text='Внутренняя ссылка (например /catalog/) или полный URL', label='Ссылка кнопки', max_length=200, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Фоновое изображение', required=False))])), ('about', wagtail.blocks.StructBlock([('tagline', wagtail.blocks.CharBlock(label='Тег', max_length=100, required=False)), ('title', wagtail.blocks.CharBlock(label='Заголовок', max_length=200)), ('body', wagtail.blocks.RichTextBlock(label='Текст')), ('detail_one', wagtail.blocks.CharBlock(label='Деталь 1', max_length=100, required=False)), ('detail_two', wagtail.blocks.CharBlock(label='Деталь 2', max_length=100, required=False)), ('detail_three', wagtail.blocks.CharBlock(label='Деталь 3', max_length=100, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение', required=False)), ('cta_text', wagtail.blocks.CharBlock(label='Текст ссылки (необязательно)', max_length=100, required=False)), ('cta_url', wagtail.blocks.CharBlock(help_text='Внутренняя ссылка (например /catalog/) или полный URL', label='Ссылка (необязательно)', max_length=200, required=False))])), ('collections', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Заголовок секции', max_length=200)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Название', max_length=100)), ('subtitle', wagtail.blocks.CharBlock(label='Подзаголовок', max_length=200, required=False)), ('description', wagtail.blocks.TextBlock(label='Описание', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение', required=False)), ('link_text', wagtail.blocks.CharBlock(default='Смотреть', label='Текст ссылки', max_length=50)), ('link_url', wagtail.blocks.CharBlock(default='#', label='Ссылка', max_length=200, required=False))]), label='Карточки'))])), ('fabric', wagtail.blocks.StructBlock([('tagline', wagtail.blocks.CharBlock(label='Тег', max_length=100, required=False)), ('title', wagtail.blocks.CharBlock(label='Заголовок', max_length=200)), ('body', wagtail.blocks.RichTextBlock(label='Текст')), ('stat_one_value', wagtail.blocks.CharBlock(label='Показатель 1: значение', max_length=50, required=False)), ('stat_one_label', wagtail.blocks.CharBlock(label='Показатель 1: подпись', max_length=100, required=False)), ('stat_two_value', wagtail.blocks.CharBlock(label='Показатель 2: значение', max_length=50, required=False)), ('stat_two_label', wagtail.blocks.CharBlock(label='Показатель 2: подпись', max_length=100, required=False)), ('stat_three_value', wagtail.blocks.CharBlock(label='Показатель 3: значение', max_length=50, required=False)), ('stat_three_label', wagtail.blocks.CharBlock(label='Показатель 3: подпись', max_length=100, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение', required=False))])), ('philosophy', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock(label='Цитата / философия')), ('attribution', wagtail.blocks.CharBlock(label='Подпись', max_length=100, required=False)), ('body', wagtail.blocks.RichTextBlock(label='Текст', required=False)), ('cta_text', wagtail.blocks.CharBlock(label='Текст ссылки (необязательно)', max_length=100, required=False)), ('cta_url', wagtail.blocks.CharBlock(help_text='Внутренняя ссылка (например /catalog/) или полный URL', label='Ссылка (необязательно)', max_length=200, required=False))]))], blank=True, use_json_field=True),
        ),
    ]
