# Generated by Django 4.2.29 on 2026-09-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_aboutpage_body_alter_productpage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_token',
            field=models.CharField(blank=True, editable=False, help_text='Уникален: повторный POST той же формы checkout не создаёт второй заказ.', max_length=64, null=True, unique=True, verbose_name='Ключ отправки формы'),
        ),
    ]
