# Generated by Django 4.2.29 on 2026-09-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_order_checkout_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='fit_notes',
            field=models.TextField(blank=True, help_text='По одному пункту на строку, например: «Свободная посадка», «Спущенное плечо». Первая строка попадает в краткие характеристики. Пусто — блок «Как сидит» не показывается.', verbose_name='Посадка'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='model_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рост модели, см'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='model_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=4, verbose_name='Размер на модели'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_summary',
            field=models.TextField(blank=True, default='Доставка по России\nСДЭК · Яндекс Доставка · Почта России\nСтоимость рассчитывается при оформлении', help_text='Первая строка — заголовок, остальные — пояснения. Пусто — строка не показывается.', verbose_name='Доставка — коротко (под кнопкой)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_summary',
            field=models.TextField(blank=True, default='Оплата\nБанковской картой на сайте', help_text='Первая строка — заголовок, остальные — пояснения. Пусто — строка не показывается.', verbose_name='Оплата — коротко (под кнопкой)'),
        ),
    ]
