# Generated by Django 4.2.29 on 2026-07-31 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('personal_data_consent', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('consent_given_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
