# Generated by Django 4.2.29 on 2026-03-16 21:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', wagtail.blocks.StructBlock([('headline', wagtail.blocks.CharBlock(label='Главный заголовок', max_length=200)), ('subheadline', wagtail.blocks.CharBlock(label='Подзаголовок', max_length=300, required=False)), ('cta_text', wagtail.blocks.CharBlock(default='Смотреть коллекцию', label='Текст кнопки', max_length=100)), ('cta_url', wagtail.blocks.URLBlock(label='Ссылка кнопки', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Фоновое изображение', required=False))])), ('about', wagtail.blocks.StructBlock([('tagline', wagtail.blocks.CharBlock(label='Тег', max_length=100, required=False)), ('title', wagtail.blocks.CharBlock(label='Заголовок', max_length=200)), ('body', wagtail.blocks.RichTextBlock(label='Текст')), ('detail_one', wagtail.blocks.CharBlock(label='Деталь 1', max_length=100, required=False)), ('detail_two', wagtail.blocks.CharBlock(label='Деталь 2', max_length=100, required=False)), ('detail_three', wagtail.blocks.CharBlock(label='Деталь 3', max_length=100, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение', required=False))])), ('collections', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Заголовок секции', max_length=200)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Название', max_length=100)), ('subtitle', wagtail.blocks.CharBlock(label='Подзаголовок', max_length=200, required=False)), ('description', wagtail.blocks.TextBlock(label='Описание', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение', required=False)), ('link_text', wagtail.blocks.CharBlock(default='Смотреть', label='Текст ссылки', max_length=50))]), label='Карточки'))])), ('marquee', wagtail.blocks.StructBlock([('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Текст', max_length=100))]), label='Элементы строки'))])), ('features', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Заголовок секции', max_length=200)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Заголовок', max_length=100)), ('description', wagtail.blocks.TextBlock(label='Описание'))]), label='Преимущества'))])), ('fabric', wagtail.blocks.StructBlock([('tagline', wagtail.blocks.CharBlock(label='Тег', max_length=100, required=False)), ('title', wagtail.blocks.CharBlock(label='Заголовок', max_length=200)), ('body', wagtail.blocks.RichTextBlock(label='Текст')), ('stat_one_value', wagtail.blocks.CharBlock(label='Показатель 1: значение', max_length=50, required=False)), ('stat_one_label', wagtail.blocks.CharBlock(label='Показатель 1: подпись', max_length=100, required=False)), ('stat_two_value', wagtail.blocks.CharBlock(label='Показатель 2: значение', max_length=50, required=False)), ('stat_two_label', wagtail.blocks.CharBlock(label='Показатель 2: подпись', max_length=100, required=False)), ('stat_three_value', wagtail.blocks.CharBlock(label='Показатель 3: значение', max_length=50, required=False)), ('stat_three_label', wagtail.blocks.CharBlock(label='Показатель 3: подпись', max_length=100, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение', required=False))])), ('featured_products', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Заголовок секции', max_length=200)), ('products', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(label='Название', max_length=100)), ('collection', wagtail.blocks.CharBlock(label='Коллекция', max_length=100, required=False)), ('price', wagtail.blocks.CharBlock(label='Цена', max_length=50, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Изображение', required=False)), ('tag', wagtail.blocks.CharBlock(label='Тег', max_length=50, required=False))]), label='Товары'))])), ('philosophy', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock(label='Цитата / философия')), ('attribution', wagtail.blocks.CharBlock(label='Подпись', max_length=100, required=False)), ('body', wagtail.blocks.RichTextBlock(label='Текст', required=False))])), ('cta', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Заголовок', max_length=200)), ('subtitle', wagtail.blocks.CharBlock(label='Подзаголовок', max_length=300, required=False)), ('cta_text', wagtail.blocks.CharBlock(label='Текст кнопки', max_length=100)), ('cta_url', wagtail.blocks.CharBlock(default='/collection/', label='Ссылка', max_length=200))]))], blank=True, use_json_field=True)),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
            bases=('wagtailcore.page',),
        ),
    ]
